import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {useLocale} from 'next-intl';
import {notFound} from 'next/navigation';
 
const locales = ['en', 'es'];

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Probando intl y tailwind',
  description: 'Generated by create next app',
}

export default function LocaleLayout({
  children,
  params: {locale}
}: {
  children: React.ReactNode,
  params: any
}) {
  // Validate that the incoming `locale` parameter is valid
  const isValidLocale = locales.some((cur) => cur === locale);
  if (!isValidLocale) notFound();
 
  return (
    <html lang={locale}>
      <body>{children}</body>
    </html>
  );
}
